python -c "from test40assert import test_prime; test_prime(1, False)"
python -c "from test40assert import test_prime; test_prime(4, False)"
python -c "from test40assert import test_prime; test_prime(5, True)"
python -c "from test40assert import test_prime; test_prime(11, True)"
python -c "from test40assert import test_prime; test_prime(14, False)"
python -c "from test40assert import test_prime; test_prime(21, False)"
python -c "from test40assert import test_prime; test_prime(22, True)"